### ISSUE TITLE
Simple implementation of MCMC methods

### ISSUE THREAD

**Issue by scidom** [JuliaStats/MCMC.jl#11]
Hi everyone,

As some of you may know, I will be writing a book on Monte Carlo methods with Julia. The book will be a textbook, not a monograph, i.e. it will be pedagogical rather than research-oriented. Along these lines, I will be providing a simple implementation of basic Monte Carlo methods (and in subsequent complementary subsections examples of how to use Lora for the same methods).

Along these lines, I will need to provide a very simple implementation of basic MCMC routines. Is it ok if I do this in JuliaStats/MCMC.jl or would you prefer I do it in a separate repository? I will wait for 3-4 days to hear what you have to say before I proceed.

Best,
Theo

**Comment by dmbates** [comment]
The name `JuliaStats/MCMC.jl` for a repository carries a certain imprimatur of being the official or preferred implementation of MCMC in Julia.  Currently its `README.md` file says that it will be a location for a merging of currently independent MCMC implementations in Julia.  I think I would rather reserve the name for this or for a sort of "super-package" that points to different implementations including [Mamba](https://github.com/brian-j-smith/Mamba.jl] and [Stan](https://github.com/goedman/Stan.jl).

If the implementation is for illustration in your book wouldn't it be more appropriate that it be housed in a repository associated with the book?

**Comment by scidom** [comment]
Yes, of course, happy to do as you suggested.  Asked because there was a suggestion a while back that we may use MCMC.jl to host a simple implementation for MCMC rather than a meta-package that would have a meta-related name.

**Comment by scidom** [comment]
P.S. Such a meta-package would include Lora among other packages I presume? ;)

**Comment by simonbyrne** [comment]
I would suggest a separate repository, perhaps one with the same name as the book?

**Comment by scidom** [comment]
Thanks, Simon. Yes, I will create a standalone repository, will close this issue in this case.
